In [1]:
import glob
import numpy as np
import pandas as pd

In [2]:
# MinTic dataset used to extract the municipalities to use

mun = pd.read_csv('data/comp_dim_clean.csv')

In [3]:
mun.head(1)

anio_corte municipio  codigo departamento grupo_dotaciones  \
0        2016  medellin    5001    antioquia                c   

      categoria_de_ruralidad  cobertura_media_neta  saber_11_matematicas  \
0  ciudades_y_aglomeraciones                 0.559                 49.26   

   saber_11_lenguaje  cobertura_transicion  ...  cobertura_internet  \
0               51.7                 0.737  ...               0.214   

   cobertura_acueducto  cobertura_alcantarillado  hurtos  hurtos_x_10000_hab  \
0                 0.97                      0.92   13871               55.78   

   homicidios  homicidios_x_10000_hab  violencia_intrafamiliar  \
0         536                    2.16                     2374   

   violencia_intrafamiliar_x_10000_hab        id  
0                                 9.55  20165001  

[1 rows x 24 columns]

In [4]:
municipios = mun.codigo.unique()
len(municipios)

1101

In [5]:
# Creating a list with the location of the TerriData datasets

terridata = glob.glob('data/TerriData*.csv')
len(terridata)

18

In [6]:
terridata

['data\\TerriData_ambiente.csv',
 'data\\TerriData_censo_2005_y_proyecciones_dane.csv',
 'data\\TerriData_conflicto_armado_y_seguridad_ciudadana.csv',
 'data\\TerriData_demografia_y_poblacion.csv',
 'data\\TerriData_descripcion_general.csv',
 'data\\TerriData_economia.csv',
 'data\\TerriData_educacion.csv',
 'data\\TerriData_finanzas_publicas.csv',
 'data\\TerriData_justicia_y_derecho.csv',
 'data\\TerriData_medicion_de_desempenio_municipal.csv',
 'data\\TerriData_mercado_laboral.csv',
 'data\\TerriData_ordenamiento_territorial.csv',
 'data\\TerriData_percepcion_ciudadana.csv',
 'data\\TerriData_pobreza.csv',
 'data\\TerriData_presupuesto_general_de_la_nacion.csv',
 'data\\TerriData_salud.csv',
 'data\\TerriData_seguridad_integral_maritima_y_fluvial.csv',
 'data\\TerriData_vivienda_y_acceso_a_servicios_publicos.csv']

In [12]:
# Function to check the number of municipalities with data for each year

def check_mun(df, municipios):
    anios = df.anio.unique()
    for anio in anios:
        mun_df = df.loc[df.anio.eq(anio)].codigo_entidad.unique()
        print(f'Number of unique mun for {anio}: {len(mun_df)}')
        print('Mun not in MinTic databases')
        print(list(set(municipios) - set(mun_df)))

#### Ambiente

In [13]:
# Loading and filtering the csv

ambi = pd.read_csv(terridata[0])
ambi = ambi.loc[ambi.codigo_entidad.isin(municipios)
                & ambi.anio.ge(2016)
                & ambi.anio.le(2019)]
ambi.head(1)

c:\users\seb\appdata\local\programs\python\python39\lib\site-packages\IPython\core\interactiveshell.py:3441: DtypeWarning: Columns (9) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


Unnamed: 0  codigo_departamento departamento  codigo_entidad entidad  \
0     3448811                   97       vaupes           97161  caruru   

  dimension                                       subcategoria  \
0  ambiente  biodiversidad_y_servicios_ecosistemicos:_area_...   

                                           indicador  dato_numerico  \
0  area_de_la_entidad_territorial_que_hace_parte_...        8342.85   

  dato_cualitativo  anio  mes                        fuente unidad_de_medida  
0              NaN  2017   12  parques_nacionales_naturales        hectareas

In [10]:
# Checking the years where there is data

anio = ambi.anio.unique()
anio.sort()
anio

array([2016, 2017, 2018], dtype=int64)

There  is no data for 2019.

In [11]:
# Variables in the dataset

ambi.indicador.unique()

array(['area_de_la_entidad_territorial_que_hace_parte_del_sinap',
       'porcentaje_del_area_de_la_entidad_territorial_que_hace_parte_del_sinap',
       'porcentaje_del_area_departamental_en_el_sinap_que_se_encuentra_en_el_municipio',
       'area_de_humedales', 'area_de_paramos',
       'area_total_de_ecosistemas_estrategicos',
       'porcentaje_del_area_de_humedales',
       'porcentaje_del_area_de_paramos',
       'porcentaje_del_area_total_de_ecosistemas_estrategicos',
       'porcentaje_del_area_departamental_en_humedales_que_se_encuentra_en_el_municipio',
       'porcentaje_del_area_departamental_en_paramos_que_se_encuentra_en_el_municipio',
       'area_de_bosque_estable_de_la_entidad_territorial',
       'area_deforestada_en_la_entidad_territorial',
       'porcentaje_del_area_departamental_de_bosque_que_se_encuentra_en_el_municipio',
       'porcentaje_del_area_departamental_deforestada_que_ocurrio_en_el_municipio',
       'porcentaje_del_area_nacional_de_bosque_que_se_encue

In [14]:
# Filtering the data by the variable selected

ambi_1 = ambi.loc[ambi.indicador.eq('inversion_en_adaptacion_al_cambio_climatico')]
ambi_1.anio.unique()

array([2016, 2017], dtype=int64)

In [18]:
# Filtering the data by the variable selected

ambi_1 = ambi.loc[ambi.indicador.eq('inversion_en_adaptacion_-_mitigacion')]
ambi_1.anio.unique()

array([2016, 2017], dtype=int64)

In [16]:
# Filtering the data by the variable selected

ambi_1 = ambi.loc[ambi.indicador.eq('indice_de_vulnerabilidad_y_riesgo_por_cambio_climatico')]
ambi_1.anio.unique()

array([2017], dtype=int64)

In [17]:
# Filtering the data by the variable selected

ambi_1 = ambi.loc[ambi.indicador.eq('indice_de_riesgo_ajustado_por_capacidades')]
ambi_1.anio.unique()

array([2018], dtype=int64)

There is no useful variable with enough years of data.

#### Demografia

In [19]:
# Loading and filtering the csv

demo = pd.read_csv(terridata[3])
demo = demo.loc[demo.codigo_entidad.isin(municipios)
                & demo.anio.ge(2016)
                & demo.anio.le(2019)]
demo.head(1)

Unnamed: 0  codigo_departamento departamento  codigo_entidad entidad  \
0       23814                   97       vaupes           97161  caruru   

                dimension          subcategoria  \
0  demografia_y_poblacion  poblacion_de_hombres   

                       indicador  dato_numerico  dato_cualitativo  anio  mes  \
0  poblacion_de_hombres_de_00-04          198.0               NaN  2018   12   

                                          fuente unidad_de_medida  
0  dane_-_censo_nacional_de_poblacion_y_vivienda          hombres

In [20]:
# Checking the years where there is data

anio = demo.anio.unique()
anio.sort()
anio

array([2016, 2017, 2018, 2019], dtype=int64)

In [21]:
# Variables in the dataset

demo.indicador.unique()

array(['poblacion_de_hombres_de_00-04', 'poblacion_de_hombres_de__05-09',
       'poblacion_de_hombres_de__10-14', 'poblacion_de_hombres_de__15-19',
       'poblacion_de_hombres_de__20-24', 'poblacion_de_hombres_de__25-29',
       'poblacion_de_hombres_de__30-34', 'poblacion_de_hombres_de__35-39',
       'poblacion_de_hombres_de__40-44', 'poblacion_de_hombres_de__45-49',
       'poblacion_de_hombres_de__50-54', 'poblacion_de_hombres_de__55-59',
       'poblacion_de_hombres_de__60-64', 'poblacion_de_hombres_de__65-69',
       'poblacion_de_hombres_de__70-74', 'poblacion_de_hombres_de__75-79',
       'poblacion_de_hombres_de_80_o_mas',
       'porcentaje_de_poblacion_de_hombres_de_00-04',
       'porcentaje_de_poblacion_de_hombres_de__05-09',
       'porcentaje_de_poblacion_de_hombres_de__10-14',
       'porcentaje_de_poblacion_de_hombres_de__15-19',
       'porcentaje_de_poblacion_de_hombres_de__20-24',
       'porcentaje_de_poblacion_de_hombres_de__25-29',
       'porcentaje_de_poblaci

In [22]:
# Filtering the data by the variable selected
demo_1 = demo.loc[demo.indicador.eq('puntaje_sisben:_minimo_-_total')]
demo_1.anio.unique()

array([2017], dtype=int64)

In [23]:
# Filtering the data by the variable selected
demo_1 = demo.loc[demo.indicador.eq('puntaje_sisben:_minimo_-_cabecera')]
demo_1.anio.unique()

array([2017], dtype=int64)

The useful variables have not enough years of data.

#### Economia

In [25]:
# Loading and filtering the csv

econo = pd.read_csv(terridata[5])
econo = econo.loc[econo.codigo_entidad.isin(municipios)
                  & econo.anio.ge(2016)
                  & econo.anio.le(2019)]
econo.head(1)

c:\users\seb\appdata\local\programs\python\python39\lib\site-packages\IPython\core\interactiveshell.py:3441: DtypeWarning: Columns (9) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


Unnamed: 0  codigo_departamento  departamento  codigo_entidad  \
104634     3735294                   25  cundinamarca           25489   

        entidad dimension                                       subcategoria  \
104634  nimaima  economia  principales_cultivos_transitorios_segun_produc...   

                                                indicador  dato_numerico  \
104634  primer_cultivo_transitorio_en_terminos_de_tone...           38.0   

       dato_cualitativo  anio  mes  \
104634             Maíz  2016   12   

                                                   fuente unidad_de_medida  
104634  evaluacion_agropecuaria_municipal;_minagricultura           numero

In [26]:
# Checking the years where there is data

anio = econo.anio.unique()
anio.sort()
anio

array([2016, 2017, 2018], dtype=int64)

2019 is missing.

In [27]:
# Variables in the dataset

econo.indicador.unique()

array(['primer_cultivo_transitorio_en_terminos_de_toneladas_producidas',
       'segundo_cultivo_transitorio_en_terminos_de_toneladas_producidas',
       'tercer_cultivo_transitorio_en_terminos_de_toneladas_producidas',
       'toneladas_producidas_por_otros_cultivos_transitorios',
       'participacion_del_primer_cultivo_transitorio_en_la_produccion_total_de_los_cultivos_transitorios',
       'participacion_del_segundo_cultivo_transitorio_en_la_produccion_total_de_los_cultivos_transitorios',
       'participacion_del_tercer_cultivo_transitorio_en_la_produccion_total_de_los_cultivos_transitorios',
       'participacion_de_los_demas_cultivos_transitorios_en_la_produccion_total_de_cultivos_transitorios',
       'primer_cultivo_permanente_en_terminos_de_toneladas_producidas',
       'segundo_cultivo_permanente_en_terminos_de_toneladas_producidas',
       'tercer_cultivo_permanente_en_terminos_de_toneladas_producidas',
       'toneladas_producidas_por_otros_cultivos_permanentes',
       'p

In [28]:
# Filtering the data by the variable selected
econo_1 = econo.loc[econo.indicador.eq('valor_agregado')]
econo_1.anio.unique()

array([2016, 2017, 2018], dtype=int64)

In [31]:
# Using the custom function to check for missing municipalities
check_mun(econo_1, municipios)

Number of unique mun for 2016: 1101
Mun not in MinTic databases
[]
Number of unique mun for 2017: 1101
Mun not in MinTic databases
[]
Number of unique mun for 2018: 1101
Mun not in MinTic databases
[]


In [30]:
# Filtering the data by the variable selected
econo_2 = econo.loc[econo.indicador.eq('valor_agregado_per_capita')]
econo_2.anio.unique()

array([2016, 2017, 2018], dtype=int64)

In [32]:
# Using the custom function to check for missing municipalities
check_mun(econo_2, municipios)

Number of unique mun for 2016: 1101
Mun not in MinTic databases
[]
Number of unique mun for 2017: 1101
Mun not in MinTic databases
[]
Number of unique mun for 2018: 1101
Mun not in MinTic databases
[]


The useful variables are missing 2019.

#### Educacion

In [33]:
# Loading and filtering the csv

edu = pd.read_csv(terridata[6])
edu = edu.loc[edu.codigo_entidad.isin(municipios)
              & edu.anio.ge(2016)
              & edu.anio.le(2019)]
edu.head(1)

Unnamed: 0  codigo_departamento departamento  codigo_entidad  entidad  \
12475     1038610                   44   la_guajira           44035  albania   

       dimension           subcategoria                      indicador  \
12475  educacion  acceso_a_la_educacion  cobertura_bruta_en_transicion   

       dato_numerico  dato_cualitativo  anio  mes  \
12475         136.75               NaN  2016   12   

                                 fuente  \
12475  ministerio_de_educacion_nacional   

                                      unidad_de_medida  
12475  porcentaje_(el_valor_esta_multiplicado_por_100)

In [35]:
# Checking the years where there is data

anio = edu.anio.unique()
anio.sort()
anio

array([2016, 2017, 2018, 2019], dtype=int64)

In [34]:
# Variables in the dataset

edu.indicador.unique()

array(['cobertura_bruta_en_transicion',
       'cobertura_bruta_en_educacion_primaria',
       'cobertura_bruta_en_educacion_secundaria',
       'cobertura_bruta_en_educacion_media',
       'cobertura_bruta_en_educacion_basica',
       'cobertura_bruta_en_educacion_-_total',
       'cobertura_neta_en_transicion',
       'cobertura_neta_en_educacion_primaria',
       'cobertura_neta_en_educacion_secundaria',
       'cobertura_neta_en_educacion_media',
       'cobertura_neta_en_educacion_basica',
       'cobertura_neta_en_educacion_-_total',
       'tasa_de_desercion_intra-anual_del_sector_oficial_en_educacion_basica_y_media_(desde_transicion_hasta_once)',
       'tasa_de_repitencia_del_sector_oficial_en_educacion_basica_y_media_(desde_transicion_hasta_once)',
       'tasa_de_analfabetismo_(censo)',
       'tasa_de_analfabetismo_urbana_(censo)',
       'tasa_de_analfabetismo_rural_(censo)',
       'porcentaje_de_asistencia_de_5_a_24_anios_(censo)',
       'porcentaje_de_asistencia_de_5_a

In [36]:
# Filtering the data by the variable selected
edu_1 = edu.loc[edu.indicador.eq('cobertura_neta_en_educacion_-_total')]
edu_1.anio.unique()

array([2016, 2017, 2018, 2019], dtype=int64)

In [37]:
# Using the custom function to check for missing municipalities
check_mun(edu_1, municipios)

Number of unique mun for 2016: 1101
Mun not in MinTic databases
[]
Number of unique mun for 2017: 1101
Mun not in MinTic databases
[]
Number of unique mun for 2018: 1101
Mun not in MinTic databases
[]
Number of unique mun for 2019: 1101
Mun not in MinTic databases
[]


In [39]:
# Filtering the data by the variable selected
edu_2 = edu.loc[edu.indicador.eq('cobertura_neta_en_educacion_basica')]
edu_2.anio.unique()

array([2016, 2017, 2018], dtype=int64)

In [40]:
# Using the custom function to check for missing municipalities
check_mun(edu_2, municipios)

Number of unique mun for 2016: 1101
Mun not in MinTic databases
[]
Number of unique mun for 2017: 1101
Mun not in MinTic databases
[]
Number of unique mun for 2018: 1101
Mun not in MinTic databases
[]


2019 missing.

In [41]:
# Filtering the data by the variable selected
edu_3 = edu.loc[edu.indicador.eq('tasa_de_analfabetismo_(censo)')]
edu_3.anio.unique()

array([2018], dtype=int64)

There is une variable with the 4 years and another one with 3.

#### Finanzas

In [42]:
# Loading and filtering the csv

finanzas = pd.read_csv(terridata[7])
finanzas = finanzas.loc[finanzas.codigo_entidad.isin(municipios)
                        & finanzas.anio.ge(2016)
                        & finanzas.anio.le(2019)]
finanzas.head(1)

Unnamed: 0  codigo_departamento departamento  codigo_entidad   entidad  \
18144     1991906                   23      cordoba           23855  valencia   

               dimension                   subcategoria         indicador  \
18144  finanzas_publicas  operaciones_efectivas_de_caja  ingresos_totales   

       dato_numerico  dato_cualitativo  anio  mes  \
18144       37106.64               NaN  2016   12   

                                    fuente              unidad_de_medida  
18144  dnp_a_partir_de_informacion_del_fut  millones_de_pesos_corrientes

In [43]:
# Checking the years where there is data

anio = finanzas.anio.unique()
anio.sort()
anio

array([2016, 2017, 2018, 2019], dtype=int64)

In [44]:
# Variables in the dataset

finanzas.indicador.unique()

array(['ingresos_totales', 'ingresos_corrientes', 'ingresos_tributarios',
       'ingresos_no_tributarios',
       'transferencias_de_los_ingresos_corrientes', 'gastos_totales',
       'gastos_corrientes', 'funcionamiento',
       'intereses_de_deuda_publica', 'deficit_o_ahorro_corriente',
       'ingresos_de_capital', 'gastos_de_capital_(inversion)',
       'deficit_o_superavit_total', 'financiamiento',
       'credito_interno_y_externo',
       'recursos_del_balance_y_variacion_de_depositos',
       'ingresos_totales_per_capita', 'ingresos_corrientes_per_capita',
       'ingresos_tributarios_per_capita',
       'ingresos_per_capita_por_impuesto_predial',
       'ingresos_per_capita_por_impuesto_a_la_industria_y_al_comercio',
       'ingresos_no_tributarios_per_capita', 'gastos_totales_per_capita',
       'gastos_corrientes_per_capita',
       'gastos_de_funcionamiento_per_capita',
       'regalias_per_capita_(valor_efectivamente_girado_al_municipio)',
       'transferencias_per_capit

In [49]:
# Filtering the data by the variable selected
fin_1 = finanzas.loc[finanzas.indicador.eq('ingresos_totales_per_capita')]
fin_1.anio.unique()

array([2016, 2017, 2018, 2019], dtype=int64)

In [50]:
# Using the custom function to check for missing municipalities
check_mun(fin_1, municipios)

Number of unique mun for 2016: 1101
Mun not in MinTic databases
[]
Number of unique mun for 2017: 1101
Mun not in MinTic databases
[]
Number of unique mun for 2018: 1101
Mun not in MinTic databases
[]
Number of unique mun for 2019: 1101
Mun not in MinTic databases
[]


In [54]:
# Filtering the data by the variable selected
fin_2 = finanzas.loc[finanzas.indicador.eq('gastos_totales_per_capita')]
fin_2.anio.unique()

array([2016, 2017, 2018, 2019], dtype=int64)

In [58]:
# Using the custom function to check for missing municipalities
check_mun(fin_2, municipios)

Number of unique mun for 2016: 1101
Mun not in MinTic databases
[]
Number of unique mun for 2017: 1101
Mun not in MinTic databases
[]
Number of unique mun for 2018: 1101
Mun not in MinTic databases
[]
Number of unique mun for 2019: 1101
Mun not in MinTic databases
[]


In [55]:
# Filtering the data by the variable selected
fin_3 = finanzas.loc[finanzas.indicador.eq('total_de_recursos_asignados_per_capita_-_sgp')]
fin_3.anio.unique()

array([2016, 2017], dtype=int64)

In [56]:
# Filtering the data by the variable selected
fin_3 = finanzas.loc[finanzas.indicador.eq('valor_de_los_proyectos_terminados')]
fin_3.anio.unique()

array([2016, 2017, 2018], dtype=int64)

In [57]:
# Using the custom function to check for missing municipalities
check_mun(fin_3, municipios)

Number of unique mun for 2016: 4
Mun not in MinTic databases
[20517, 41001, 73770, 41006, 41013, 41016, 41020, 41026, 20550, 20570, 8296, 41078, 73854, 73861, 20614, 20621, 73870, 73873, 41132, 8372, 86219, 8421, 20710, 8433, 8436, 41206, 20750, 41244, 20770, 86320, 20787, 8520, 41298, 41306, 8549, 41319, 8558, 8560, 70001, 8573, 41349, 41357, 41359, 8606, 41378, 25001, 41396, 8634, 25019, 8638, 25035, 25040, 66001, 25053, 70110, 8675, 70124, 8685, 66045, 25086, 25095, 25099, 41483, 66075, 41503, 25120, 25123, 25126, 66088, 86568, 86569, 86571, 86573, 41518, 41524, 8758, 41530, 25148, 70204, 25151, 8770, 25154, 70215, 41548, 70221, 41551, 25168, 70230, 25175, 70233, 25178, 70235, 25181, 25183, 17001, 25200, 17013, 70265, 66170, 25214, 8832, 25224, 41615, 8849, 17042, 17050, 25245, 25258, 25260, 25269, 99001, 41660, 25279, 17088, 25281, 41668, 25286, 25288, 13001, 25290, 41676, 25293, 13006, 25295, 25297, 25299, 25307, 86749, 25312, 86755, 86757, 25317, 13030, 86760, 25320, 25322, 25324

In [59]:
# Filtering the data by the variable selected
fin_3 = finanzas.loc[finanzas.indicador.eq('indice_de_gestion_de_proyectos_de_regalias_(igpr)')]
fin_3.anio.unique()

array([2016, 2017, 2018, 2019], dtype=int64)

In [61]:
# Using the custom function to check for missing municipalities
check_mun(fin_3, municipios)

Number of unique mun for 2016: 1101
Mun not in MinTic databases
[]
Number of unique mun for 2017: 1101
Mun not in MinTic databases
[]
Number of unique mun for 2018: 1101
Mun not in MinTic databases
[]
Number of unique mun for 2019: 1101
Mun not in MinTic databases
[]


In [62]:
# Filtering the data by the variable selected
fin_4 = finanzas.loc[finanzas.indicador.eq('indicador_de_desempenio_fiscal')]
fin_4.anio.unique()

array([2016, 2017, 2018], dtype=int64)

In [63]:
# Using the custom function to check for missing municipalities
check_mun(fin_4, municipios)

Number of unique mun for 2016: 1101
Mun not in MinTic databases
[]
Number of unique mun for 2017: 1101
Mun not in MinTic databases
[]
Number of unique mun for 2018: 1101
Mun not in MinTic databases
[]


#### Justicia

In [67]:
# Loading and filtering the csv

jus = pd.read_csv(terridata[8])
jus = jus.loc[jus.codigo_entidad.isin(municipios)
              & jus.anio.ge(2016)
              & jus.anio.le(2019)]
jus.head(1)

c:\users\seb\appdata\local\programs\python\python39\lib\site-packages\IPython\core\interactiveshell.py:3441: DtypeWarning: Columns (9) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


Unnamed: 0  codigo_departamento departamento  codigo_entidad  \
0     4360997                   86     putumayo           86865   

             entidad           dimension  \
0  valle_del_guamuez  justicia_y_derecho   

                                        subcategoria  \
0  conciliacion_extrajudicial_en_derecho_por_area...   

                              indicador  dato_numerico dato_cualitativo  anio  \
0  acuerdo_-_derecho__civil_y_comercial            NaN              NaN  2016   

   mes                               fuente  \
0   12  ministerio_de_justicia_y_el_derecho   

                          unidad_de_medida  
0  puntos_porcentuales_(escala_de_0_a_100)

In [68]:
# Checking the years where there is data

anio = jus.anio.unique()
anio.sort()
anio

array([2016, 2017, 2018, 2019], dtype=int64)

In [69]:
# Variables in the dataset

jus.indicador.unique()

array(['acuerdo_-_derecho__civil_y_comercial',
       'acuerdo_-_derecho_comunitario',
       'acuerdo_-_derecho_contencioso_administrativo',
       'acuerdo_-_asuntos_especiales', 'acuerdo_-_derecho_de_familia',
       'acuerdo_-_asuntos_familiares', 'acuerdo_-_derecho_laboral',
       'acuerdo_-_derecho_penal',
       'acuerdo_-_derecho_de_propiedad_intelectual',
       'acuerdo_-_area_del_derecho_no_definida',
       'acuerdo_-_todas_las_ramas_del_derecho',
       'inasistencia_-_derecho__civil_y_comercial',
       'inasistencia_-_derecho_comunitario',
       'inasistencia_-_derecho_contencioso_administrativo',
       'inasistencia_-_asuntos_especiales',
       'inasistencia_-_derecho_de_familia',
       'inasistencia_-_asuntos_familiares',
       'inasistencia_-_derecho_laboral', 'inasistencia_-_derecho_penal',
       'inasistencia_-_derecho_de_propiedad_intelectual',
       'inasistencia_-_area_del_derecho_no_definida',
       'inasistencia_-_todas_las_ramas_del_derecho',
       '

In [70]:
# Filtering the data by the variable selected
jus_1 = jus.loc[jus.indicador.eq('barrera_de_acceso_a_la_justicia_1_slj')]
jus_1.anio.unique()

array([2017], dtype=int64)

In [71]:
# Filtering the data by the variable selected
jus_1 = jus.loc[jus.indicador.eq('barrera_de_acceso_a_la_justicia_2_slj')]
jus_1.anio.unique()

array([2017], dtype=int64)

In [72]:
# Filtering the data by the variable selected
jus_1 = jus.loc[jus.indicador.eq('conflictividad_1_slj')]
jus_1.anio.unique()

array([2017], dtype=int64)

#### Mercado Laboral

In [73]:
# Loading and filtering the csv

mer_lab = pd.read_csv(terridata[10])
mer_lab = mer_lab.loc[mer_lab.codigo_entidad.isin(municipios)
                      & mer_lab.anio.ge(2016)
                      & mer_lab.anio.le(2019)]
mer_lab.head(1)

Unnamed: 0  codigo_departamento departamento  codigo_entidad  entidad  \
7722     4176963                   44   la_guajira           44035  albania   

            dimension                                       subcategoria  \
7722  mercado_laboral  trabajadores_cotizantes_al_sistema_general_de_...   

                                         indicador  dato_numerico  \
7722  trabajadores_cotizantes_con_17_anios_o_menos            3.1   

      dato_cualitativo  anio  mes                         fuente  \
7722               NaN  2016   12  filco-_ministerio_del_trabajo   

     unidad_de_medida  
7722     trabajadores

In [74]:
# Checking the years where there is data

anio = mer_lab.anio.unique()
anio.sort()
anio

array([2016], dtype=int64)

#### Ordenamiento Territorial

In [75]:
# Loading and filtering the csv

ord_ter = pd.read_csv(terridata[11])
ord_ter = ord_ter.loc[ord_ter.codigo_entidad.isin(municipios)
                      & ord_ter.anio.ge(2016)
                      & ord_ter.anio.le(2019)]
ord_ter.head(1)

Unnamed: 0  codigo_departamento departamento  codigo_entidad  entidad  \
15877     4079912                   44   la_guajira           44035  albania   

                      dimension  \
15877  ordenamiento_territorial   

                                            subcategoria  \
15877  figuras_de_ordenamiento_social_de_la_propiedad...   

                         indicador  dato_numerico dato_cualitativo  anio  mes  \
15877  ospr_-_resguardos_indigenas       18257.09              NaN  2017   12   

                                     fuente unidad_de_medida  
15877  dnp_a_partir_de_informacion_del_igac        hectareas

In [76]:
# Checking the years where there is data

anio = ord_ter.anio.unique()
anio.sort()
anio

array([2016, 2017], dtype=int64)

#### Percepcion Ciudadana

In [77]:
# Loading and filtering the csv

per_ciu = pd.read_csv(terridata[12])
per_ciu = per_ciu.loc[per_ciu.codigo_entidad.isin(municipios)
                      & per_ciu.anio.ge(2016)
                      & per_ciu.anio.le(2019)]
per_ciu.head(1)

Unnamed: 0  codigo_departamento departamento  codigo_entidad entidad  \
11     3433285                   85     casanare           85001   yopal   

               dimension        subcategoria  indicador  dato_numerico  \
11  percepcion_ciudadana  imagen_del_alcalde  favorable            NaN   

    dato_cualitativo  anio  mes    fuente  \
11               NaN  2016   12  ciudatos   

                                   unidad_de_medida  
11  porcentaje_(el_valor_esta_multiplicado_por_100)

In [78]:
# Checking the years where there is data

anio = per_ciu.anio.unique()
anio.sort()
anio

array([2016], dtype=int64)

#### Pobreza

In [79]:
# Loading and filtering the csv

poverty = pd.read_csv(terridata[13])
poverty = poverty.loc[poverty.codigo_entidad.isin(municipios)
                      & poverty.anio.ge(2016)
                      & poverty.anio.le(2019)]
poverty.head(1)

Unnamed: 0  codigo_departamento departamento  codigo_entidad     entidad  \
769     4046528                   20        cesar           20001  valledupar   

    dimension            subcategoria                           indicador  \
769   pobreza  indicadores_de_pobreza  incidencia_de_la_pobreza_monetaria   

     dato_numerico  dato_cualitativo  anio  mes fuente  \
769           35.5               NaN  2016   12   dane   

                                    unidad_de_medida  
769  porcentaje_(el_valor_esta_multiplicado_por_100)

In [80]:
# Checking the years where there is data

anio = poverty.anio.unique()
anio.sort()
anio

array([2016, 2017, 2018], dtype=int64)

In [81]:
# Variables in the dataset

poverty.indicador.unique()

array(['incidencia_de_la_pobreza_monetaria',
       'incidencia_de_la_pobreza_monetaria_extrema',
       'coeficiente_de_gini', 'indice_de_pobreza_multidimensional_-_ipm',
       'ipm_-_cabecera', 'ipm_-_rural',
       'indice_de_necesidades_basicas_insatisfechas_-_nbi_-_en_el_area_urbana',
       'indice_de_necesidades_basicas_insatisfechas_-_nbi_-_en_el_area_rural',
       'poblacion_en_condicion_de_miseria',
       'poblacion_en_condicion_de_miseria_en_el_area_urbana',
       'poblacion_en_condicion_de_miseria_en_el_area_rural',
       'incidencia_de_pobreza_monetaria_extrema_en_hombres',
       'incidencia_de_pobreza_monetaria_extrema_en_mujeres',
       'incidencia_de_pobreza_monetaria_en_hombres',
       'incidencia_de_pobreza_monetaria_en_mujeres',
       'incidencia_de_pobreza_monetaria_extrema_en_hogares_con_jefatura_masculina',
       'incidencia_de_pobreza_monetaria_extrema_en_hogares_con_jefatura_femenina',
       'incidencia_de_pobreza_monetaria__en_hogares_con_jefatura_ma

In [82]:
# Filtering the data by the variable selected
pov_1 = poverty.loc[poverty.indicador.eq('incidencia_de_la_pobreza_monetaria')]
pov_1.anio.unique()

array([2016, 2017, 2018], dtype=int64)

In [83]:
# Using the custom function to check for missing municipalities
check_mun(pov_1, municipios)

Number of unique mun for 2016: 31
Mun not in MinTic databases
[20517, 73770, 41006, 41013, 41016, 41020, 41026, 20550, 20570, 8296, 41078, 73854, 73861, 20614, 20621, 73870, 73873, 41132, 8372, 86219, 8421, 20710, 8433, 8436, 41206, 20750, 41244, 20770, 86320, 20787, 8520, 41298, 41306, 8549, 41319, 8558, 8560, 8573, 41349, 41357, 41359, 8606, 41378, 25001, 41396, 8634, 25019, 8638, 25035, 25040, 25053, 70110, 8675, 70124, 8685, 66045, 25086, 25095, 25099, 41483, 66075, 41503, 25120, 25123, 25126, 66088, 86568, 86569, 86571, 86573, 41518, 41524, 8758, 41530, 25148, 70204, 25151, 8770, 25154, 70215, 41548, 70221, 41551, 25168, 70230, 25175, 70233, 25178, 70235, 25181, 25183, 25200, 17013, 70265, 66170, 25214, 8832, 25224, 41615, 8849, 17042, 17050, 25245, 25258, 25260, 25269, 41660, 25279, 17088, 25281, 41668, 25286, 25288, 25290, 41676, 25293, 13006, 25295, 25297, 25299, 25307, 86749, 25312, 86755, 86757, 25317, 13030, 86760, 25320, 25322, 25324, 25326, 25328, 13042, 54003, 25335, 2533

In [84]:
# Filtering the data by the variable selected
pov_1 = poverty.loc[poverty.indicador.eq('incidencia_de_la_pobreza_monetaria_extrema')]
pov_1.anio.unique()

array([2016, 2017, 2018], dtype=int64)

In [85]:
# Using the custom function to check for missing municipalities
check_mun(pov_1, municipios)

Number of unique mun for 2016: 31
Mun not in MinTic databases
[20517, 73770, 41006, 41013, 41016, 41020, 41026, 20550, 20570, 8296, 41078, 73854, 73861, 20614, 20621, 73870, 73873, 41132, 8372, 86219, 8421, 20710, 8433, 8436, 41206, 20750, 41244, 20770, 86320, 20787, 8520, 41298, 41306, 8549, 41319, 8558, 8560, 8573, 41349, 41357, 41359, 8606, 41378, 25001, 41396, 8634, 25019, 8638, 25035, 25040, 25053, 70110, 8675, 70124, 8685, 66045, 25086, 25095, 25099, 41483, 66075, 41503, 25120, 25123, 25126, 66088, 86568, 86569, 86571, 86573, 41518, 41524, 8758, 41530, 25148, 70204, 25151, 8770, 25154, 70215, 41548, 70221, 41551, 25168, 70230, 25175, 70233, 25178, 70235, 25181, 25183, 25200, 17013, 70265, 66170, 25214, 8832, 25224, 41615, 8849, 17042, 17050, 25245, 25258, 25260, 25269, 41660, 25279, 17088, 25281, 41668, 25286, 25288, 25290, 41676, 25293, 13006, 25295, 25297, 25299, 25307, 86749, 25312, 86755, 86757, 25317, 13030, 86760, 25320, 25322, 25324, 25326, 25328, 13042, 54003, 25335, 2533

In [86]:
# Filtering the data by the variable selected
pov_1 = poverty.loc[poverty.indicador.eq('coeficiente_de_gini')]
pov_1.anio.unique()

array([2016, 2017, 2018], dtype=int64)

In [87]:
# Using the custom function to check for missing municipalities
check_mun(pov_1, municipios)

Number of unique mun for 2016: 31
Mun not in MinTic databases
[20517, 73770, 41006, 41013, 41016, 41020, 41026, 20550, 20570, 8296, 41078, 73854, 73861, 20614, 20621, 73870, 73873, 41132, 8372, 86219, 8421, 20710, 8433, 8436, 41206, 20750, 41244, 20770, 86320, 20787, 8520, 41298, 41306, 8549, 41319, 8558, 8560, 8573, 41349, 41357, 41359, 8606, 41378, 25001, 41396, 8634, 25019, 8638, 25035, 25040, 25053, 70110, 8675, 70124, 8685, 66045, 25086, 25095, 25099, 41483, 66075, 41503, 25120, 25123, 25126, 66088, 86568, 86569, 86571, 86573, 41518, 41524, 8758, 41530, 25148, 70204, 25151, 8770, 25154, 70215, 41548, 70221, 41551, 25168, 70230, 25175, 70233, 25178, 70235, 25181, 25183, 25200, 17013, 70265, 66170, 25214, 8832, 25224, 41615, 8849, 17042, 17050, 25245, 25258, 25260, 25269, 41660, 25279, 17088, 25281, 41668, 25286, 25288, 25290, 41676, 25293, 13006, 25295, 25297, 25299, 25307, 86749, 25312, 86755, 86757, 25317, 13030, 86760, 25320, 25322, 25324, 25326, 25328, 13042, 54003, 25335, 2533

In [88]:
# Filtering the data by the variable selected
pov_1 = poverty.loc[poverty.indicador.eq('indice_de_pobreza_multidimensional_-_ipm')]
pov_1.anio.unique()

array([2018], dtype=int64)

#### Presupuesto

In [90]:
# Loading and filtering the csv

pres = pd.read_csv(terridata[14])
pres = pres.loc[pres.codigo_entidad.isin(municipios)
                & pres.anio.ge(2016)
                & pres.anio.le(2019)]
pres.head(1)

Empty DataFrame
Columns: [Unnamed: 0, codigo_departamento, departamento, codigo_entidad, entidad, dimension, subcategoria, indicador, dato_numerico, dato_cualitativo, anio, mes, fuente, unidad_de_medida]
Index: []

In [91]:
# Checking the years where there is data

anio = pres.anio.unique()
anio.sort()
anio

array([], dtype=int64)

#### Salud

In [92]:
# Loading and filtering the csv

salud = pd.read_csv(terridata[15])
salud = salud.loc[salud.codigo_entidad.isin(municipios)
                  & salud.anio.ge(2016)
                  & salud.anio.le(2019)]
salud.head(1)

Unnamed: 0  codigo_departamento departamento  codigo_entidad entidad  \
4537     1299418                   97       vaupes           97161  caruru   

     dimension   subcategoria                          indicador  \
4537     salud  aseguramiento  afiliados_al_regimen_contributivo   

      dato_numerico  dato_cualitativo  anio  mes  \
4537           97.0               NaN  2016   12   

                                       fuente unidad_de_medida  
4537  ministerio_de_salud_y_proteccion_social         personas

In [93]:
# Checking the years where there is data

anio = salud.anio.unique()
anio.sort()
anio

array([2016, 2017, 2018, 2019], dtype=int64)

In [94]:
# Variables in the dataset

salud.indicador.unique()

array(['afiliados_al_regimen_contributivo',
       'afiliados_al_regimen_subsidado',
       'cobertura_del_regimen_subsidiado',
       'afiliados_a_regimenes_especiales',
       'poblacion_pobre_no_atendida_-_ppna_', 'afiliados_al_sgsss',
       'tasa_de_mortalidad_(x_cada_1.000_habitantes)',
       'razon_de_mortalidad_materna_a_42_dias',
       'tasa_de_mortalidad_infantil_en_menores_de_1_anio_(x_cada_1.000_nacidos_vivos)',
       'tasa_de_fecundidad_(x_cada_1.000_mujeres_en_edad_fertil)',
       'cobertura_vacunacion_pentavalente_en_menores_de_1_anio',
       'porcentaje_de_nacidos_vivos_con_bajo_peso_al_nacer',
       'porcentaje_de_nacidos_vivos_con_4_o_mas_consultas_de_control_prenatal',
       'porcentaje_de_nacidos_vivos_hijos_de_mujeres_menores_de_14_anios',
       'promedio_de_controles_prenatales',
       'porcentaje_de_nacidos_vivos_hijos_de_mujeres_de_14_a_17_anios',
       'porcentaje_de_nacidos_vivos_hijos_de_mujeres_de_18_a_26_anios',
       'tasa_de_fecundidad_especifi

In [95]:
# Filtering the data by the variable selected
salud_1 = salud.loc[salud.indicador.eq('poblacion_pobre_no_atendida_-_ppna_')]
salud_1.anio.unique()

array([2017, 2019], dtype=int64)

In [96]:
# Filtering the data by the variable selected
salud_1 = salud.loc[salud.indicador.eq('afiliados_al_regimen_contributivo')]
salud_1.anio.unique()

array([2016, 2017, 2018, 2019], dtype=int64)

In [97]:
# Using the custom function to check for missing municipalities
check_mun(salud_1, municipios)

Number of unique mun for 2016: 1101
Mun not in MinTic databases
[]
Number of unique mun for 2017: 1101
Mun not in MinTic databases
[]
Number of unique mun for 2018: 1101
Mun not in MinTic databases
[]
Number of unique mun for 2019: 1101
Mun not in MinTic databases
[]


In [98]:
# Filtering the data by the variable selected
salud_2 = salud.loc[salud.indicador.eq('afiliados_al_regimen_subsidado')]
salud_2.anio.unique()

array([2016, 2017, 2018, 2019], dtype=int64)

In [99]:
# Using the custom function to check for missing municipalities
check_mun(salud_2, municipios)

Number of unique mun for 2016: 1101
Mun not in MinTic databases
[]
Number of unique mun for 2017: 1101
Mun not in MinTic databases
[]
Number of unique mun for 2018: 1101
Mun not in MinTic databases
[]
Number of unique mun for 2019: 1101
Mun not in MinTic databases
[]


In [100]:
# Filtering the data by the variable selected
salud_3 = salud.loc[salud.indicador.eq('afiliados_a_regimenes_especiales')]
salud_3.anio.unique()

array([2016, 2017, 2018, 2019], dtype=int64)

In [101]:
# Using the custom function to check for missing municipalities
check_mun(salud_3, municipios)

Number of unique mun for 2016: 1101
Mun not in MinTic databases
[]
Number of unique mun for 2017: 1101
Mun not in MinTic databases
[]
Number of unique mun for 2018: 1101
Mun not in MinTic databases
[]
Number of unique mun for 2019: 1101
Mun not in MinTic databases
[]


In [102]:
# Filtering the data by the variable selected
salud_4 = salud.loc[salud.indicador.eq('cobertura_del_regimen_subsidiado')]
salud_4.anio.unique()

array([2016, 2017, 2019], dtype=int64)

#### Seguridad Maritima

Not relevant for most of the municipalities.

#### Vivienda y Acceso a Servicios Publicos

In [104]:
# Loading and filtering the csv

v_ser = pd.read_csv(terridata[17])
v_ser = v_ser.loc[v_ser.codigo_entidad.isin(municipios)
                  & v_ser.anio.ge(2016)
                  & v_ser.anio.le(2019)]
v_ser.head(1)

Unnamed: 0  codigo_departamento departamento  codigo_entidad entidad  \
5670      833390                   17       caldas           17486   neira   

                                   dimension  \
5670  vivienda_y_acceso_a_servicios_publicos   

                                subcategoria  \
5670  vivienda_y_acceso_a_servicios_publicos   

                                 indicador  dato_numerico  dato_cualitativo  \
5670  cobertura_de_energia_electrica_rural          99.74               NaN   

      anio  mes fuente                                 unidad_de_medida  
5670  2016   12   upme  porcentaje_(el_valor_esta_multiplicado_por_100)

In [105]:
# Checking the years where there is data

anio = v_ser.anio.unique()
anio.sort()
anio

array([2016, 2017, 2018, 2019], dtype=int64)

In [106]:
# Variables in the dataset

v_ser.indicador.unique()

array(['cobertura_de_energia_electrica_rural',
       'penetracion_de_banda_ancha', 'cobertura_de_acueducto_(censo)',
       'cobertura_de_acueducto_(rec)',
       'cobertura_de_alcantarillado_(censo)',
       'cobertura_de_alcantarillado_(rec)',
       'deficit_cualitativo_de_vivienda_(censo)',
       'deficit_cuantitativo_de_vivienda_(censo)',
       'cobertura_de_acueducto_urbana_(rec)',
       'cobertura_de_acueducto_rural_(rec)',
       'cobertura_de_acueducto_urbana_(censo)',
       'cobertura_de_acueducto_rural_(censo)',
       'cobertura_de_alcantarillado_urbana_(rec)',
       'cobertura_de_alcantarillado_rural_(rec)',
       'cobertura_de_alcantarillado_urbana_(censo)',
       'cobertura_de_alcantarillado_rural_(censo)',
       'cobertura_de_aseo_(rec)', 'cobertura_de_aseo_(censo)',
       'cobertura_de_aseo_urbana_(rec)', 'cobertura_de_aseo_rural_(rec)',
       'cobertura_de_energia_electrica_(censo)',
       'cobertura_de_energia_electrica_urbana_(censo)',
       'cobertura_

In [107]:
# Filtering the data by the variable selected
v_ser_1 = v_ser.loc[v_ser.indicador.eq('penetracion_de_banda_ancha')]
v_ser_1.anio.unique()

array([2016, 2017, 2018, 2019], dtype=int64)

In [108]:
check_mun(v_ser_1, municipios)

Number of unique mun for 2016: 1101
Mun not in MinTic databases
[]
Number of unique mun for 2017: 1101
Mun not in MinTic databases
[]
Number of unique mun for 2018: 1101
Mun not in MinTic databases
[]
Number of unique mun for 2019: 1101
Mun not in MinTic databases
[]


In [109]:
# Filtering the data by the variable selected
v_ser_2 = v_ser.loc[v_ser.indicador.eq('cobertura_de_internet_(censo)')]
v_ser_2.anio.unique()

array([2018], dtype=int64)